# Generated by Django 4.1.3 on 2022-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='图文'),
        ),
        migrations.AddField(
            model_name='test',
            name='photo',
            field=models.CharField(default='', max_length=20, verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=models.CharField(default='', max_length=20, verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='姓名'),
        ),
    ]
