# Generated by Django 4.1.3 on 2022-11-13 08:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='test',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(null=True, upload_to='image', verbose_name='图片'),
        ),
    ]
