# Generated by Django 4.1.3 on 2022-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_test_create_time_alter_test_content_alter_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='video',
            field=models.FileField(null=True, upload_to='video', verbose_name='视频'),
        ),
    ]
